var imgWidth;
var imgHeight;
var pixels;

//the following readImageFile was generated by ChatGPT

function readImageFile(input) {
  if (input.files && input.files[0]) {
    const reader = new FileReader();

    reader.onload = function (e) {
      const img = new Image();
      img.onload = function () {
        const canvas = document.createElement("canvas");
        canvas.width = img.width;
        imgWidth=img.width;
        imgHeight=img.height;
        canvas.height = img.height;

        const ctx = canvas.getContext("2d");
        ctx.drawImage(img, 0, 0);

        const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
        const data = imageData.data;

        pixels=[];

        for (let i = 0; i < data.length; i += 4) {
          const r = data[i];
          const g = data[i + 1];
          const b = data[i + 2];
          const a = data[i + 3];
          pixels.push([r, g, b, a]);
        }

        // Display the image in the browser
        const imageContainer = document.getElementById("image-container");
        imageContainer.innerHTML = "";
        imageContainer.appendChild(img);
      };

      img.src = e.target.result;
    };

    reader.readAsDataURL(input.files[0]);
  }
}

function displayContrast(cNum) {
  console.log(cNum);
  const canvas = document.createElement('canvas');
  canvas.width = imgWidth;
  canvas.height = imgHeight;
  const context = canvas.getContext('2d');

  const imageData = context.createImageData(imgWidth, imgHeight);
  const data = imageData.data;

  goodNum=Number(cNum);
  var F = (259 * (goodNum + 255)) / (255 * (259 - goodNum));
  console.log("F:", F);
  
  for (let i = 0; i < pixels.length; i++) {
    const pixel = pixels[i];
    data[i * 4] = boundCheck((F * (pixel[0]-128)+128)); // red
    data[i * 4 + 1] = boundCheck((F * (pixel[1]-128)+128)); // green
    data[i * 4 + 2] = boundCheck((F * (pixel[2]-128)+128)); // blue
    data[i * 4 + 3] = pixel[3]; // alpha
  }
  //console.log('here322');

  context.putImageData(imageData, 0, 0);

  const img = new Image();
  img.src = canvas.toDataURL();
  const imageContainer = document.getElementById("constrast-image-container");
  imageContainer.innerHTML = "";
  imageContainer.appendChild(img);
};

function boundCheck(num){
  if(num>255)
    return 255;
  else if(num<0)
    return 0;
  else
    return num;
}